# to install etcd cluster
- hosts: etcd
  roles:
  - etcd

# to set up 'kube-master' nodes
- hosts: kube-master
  roles:
  - kube-master
  - kube-node
  tasks:
  - name: Setting master role name
    shell: "{{ bin_dir }}/kubectl label node {{ ansible_hostname }} kubernetes.io/role=master --overwrite"
    ignore_errors: true

  - name: Setting master compatible label
    shell: "{{ bin_dir }}/kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/master= --overwrite"
    ignore_errors: true

# to undeploy coredns and calico
- hosts: kube-master
  tasks:
  - name: Undeploy coredns and calico
    shell: "{{ bin_dir }}/kubectl delete -f /opt/kube/kube-system/{{ item }}"
    with_items:
    - calico.yaml  
    - coredns.yaml 
    ignore_errors: true
    run_once: true

# to install network plugin, only one can be choosen
- hosts:
  - kube-master
  roles:
  - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
  - { role: cilium, when: "CLUSTER_NETWORK == 'cilium'" }
  - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
  - { role: kube-router, when: "CLUSTER_NETWORK == 'kube-router'" }
  - { role: kube-ovn, when: "CLUSTER_NETWORK == 'kube-ovn'" }

# to install cluster-addons
- hosts:
  - kube-master
  roles:
  - cluster-addon
  tasks:
  - name: apply calico yaml again
    shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/calico.yaml"
    run_once: true

# to install kube-node-plus
- hosts:
  - kube-master
  roles:
  - kube-node-plus