# node yaml and ovn settings
  
- name: copy ovn sh
  copy: src={{ item }} dest=/etc/ansible/{{ item }}
  with_items:
  - "ovn-master.sh"
  - "ovn-node.sh"
  
- import_tasks: master.yml
  when: "inventory_hostname in groups['kube-master']"

- import_tasks: node.yml
  when: "inventory_hostname in groups['kube-node'] and inventory_hostname not in groups['kube-master']" 

- name: kubectl 软链接
  file: src={{ bin_dir }}/bin/kubectl dest=/usr/bin/kubectl state=link
  ignore_errors: true
