# master task 
- name: copy kubernetes token
  copy: src=/root/.kube/config dest=/etc/kubernetes/admin.conf

- name: deploy kubernetes custom resources
  shell: "{{ bin_dir }}/kubectl apply -f  {{ KUBEVMM_DIR }}/yamls/cloudplus"
  ignore_errors: true
  run_once: true
  
- name: deploy grafana
  shell: "{{ bin_dir }}/kubectl apply -f  {{ KUBEVMM_DIR }}/monitor/grafana.yaml"
  ignore_errors: true
  run_once: true

- name: prepare ovn-ovsdb.service config
  template: src=ovn-ovsdb.service.j2 dest=/usr/lib/systemd/system/ovn-ovsdb.service
  tags: restart_ovn

- name: prepare ovn-northd.service config
  template: src=ovn-northd.service.j2 dest=/usr/lib/systemd/system/ovn-northd.service
  tags: restart_ovn

- name: copy ovn-controller service file
  copy: src=ovn-controller.service dest=/usr/lib/systemd/system/ovn-controller.service
  tags: restart_ovn

- name: systemctl daemon-reload
  shell: "systemctl daemon-reload"
  tags: restart_ovn

- name: start openvswitch service
  service: name=openvswitch enabled=yes state=started
  tags: restart_ovn

- name: restart ovn-ovsdb service
  service: name=ovn-ovsdb enabled=yes state=restarted
  tags: restart_ovn

- name: restart ovn-northd service
  service: name=ovn-northd enabled=yes state=restarted
  tags: restart_ovn

- name: restart ovn-controller service
  service: name=ovn-controller enabled=yes state=restarted
  tags: restart_ovn

- name: set ovn-contoller params
  shell: "/bin/bash /etc/ansible/ovn-master.sh {{ inventory_hostname }}"
  tags: restart_ovn
