# node task 
- name: add vm node
  shell: "{{ bin_dir }}/kubectl apply -f  {{ KUBEVMM_DIR }}/yamls/cloudplus/node.yaml"

- name: copy ovn-controller service file
  copy: src=ovn-controller.service dest=/usr/lib/systemd/system/ovn-controller.service
  tags: restart_ovn

- name: start openvswitch service
  service: name=openvswitch enabled=yes state=started
  tags: restart_ovn

- name: restart ovn-controller service
  service: name=ovn-controller enabled=yes state=restarted
  tags: restart_ovn

- name: set ovn-contoller params
  shell: "/bin/bash /etc/ansible/ovn-node.sh {{ inventory_hostname }}"
  tags: restart_ovn

