# node task 
- name: add vm node
  shell: "{{ bin_dir }}/kubectl apply -f  {{ KUBEVMM_DIR }}/yamls/cloudplus/node.yaml"

- name: copy  ovn-controller service file
  copy: src=ovn-controller.service dest=/usr/lib/systemd/system/ovn-controller.service
  tags: restart_ovn

- name: restart ovs ovn-controller service
  shell: "systemctl daemon-reload && systemctl restart openvswitch && \
	systemctl restart ovn-controller"
  tags: restart_ovn

- name: enable ovs ovn-controller service
  shell: "systemctl enable openvswitch && systemctl enable ovn-controller"
  ignore_errors: true
  tags: restart_ovn

- name: set ovn-contoller params
  shell: "bash /etc/ansbile/ovn-node.sh {{ inventory_hostname }}"
  tags: restart_ovn

