# node task 
  
- name: copy virt-tool yaml
  copy: src={{ item }} dest={{ base_dir }}/{{ item }}
  with_items:
  - "virt-tool.yaml"

- name: deploy virt-tool yaml
  shell: "{{ bin_dir }}/kubectl --kubeconfig=/tmp/.tokenbak apply -f  {{ base_dir }}/{{ item }}"
  with_items:
  - "virt-tool.yaml"
  ignore_errors: true
  run_once: true

- name: copy ovn-controller service file
  copy: src=ovn-controller.service dest=/usr/lib/systemd/system/ovn-controller.service
  tags: restart_ovn

- name: restart openvswitch service
  service: name=openvswitch enabled=yes state=restarted
  tags: restart_ovn

- name: set ovn-contoller params
  shell: "/bin/bash /etc/ansible/ovn-node.sh {{ inventory_hostname }}"
  tags: restart_ovn

- name: restart ovn-controller service
  service: name=ovn-controller enabled=yes state=restarted
  tags: restart_ovn
