# to clean 'kube-node-plus'
- name: stop and disable ovs ovn service
  service: name={{ item }} state=stopped enabled=no
  with_items:
  - ovn-controller
  - ovn-northd
  - ovn-ovsdb
  ignore_errors: true
  
- name: delete br-int 
  shell: "ovs-vsctl --if-exists del-br br-int"
  ignore_errors: true

- name: remove files 'kube-node-plus'
  file: name={{ item }} state=absent
  with_items:
  - "/etc/ovn.conf"
  - "/usr/lib/systemd/system/ovn-ovsdb.service"
  - "/usr/lib/systemd/system/ovn-northd.service"
  - "/usr/lib/systemd/system/ovn-controller.service"
  - "/etc/openvswitch/ovnnb_db.db"
  - "/etc/openvswitch/ovnsb_db.db"
  
- name: stop kubevmm
  shell: "[ -x /usr/bin/kubevmm-adm ] && /usr/bin/kubevmm-adm service stop"
  ignore_errors: true

- name: stop host-agent
  shell: "[ -x /usr/sbin/host-agent-ctl ] && /usr/sbin/host-agent-ctl stop"
  ignore_errors: true
