apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubevirt-controller-manager
  name: kubevirt-controller-manager
  namespace: cloudplus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubevirt-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubevirt-controller-manager
    spec:
      containers:
      - command:
        - java
        - -jar
        - kubevirt-controller-1.8.0.jar
        image: registry.cn-hangzhou.aliyuncs.com/zwjhuhu/kubevirt-controller:1.8.0
        imagePullPolicy: IfNotPresent
        name: kubevirt-controller-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: admin
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /etc/kubernetes
          type: ""
        name: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt-controller-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["cloudplus.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "watch", "create", "delete"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-controller-rolebinding
  namespace: cloudplus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-controller-role
subjects:
- kind: Group
  name: system:serviceaccounts:cloudplus
  apiGroup: rbac.authorization.k8s.io
